npm i --save dotenv
npm i --save express
npm i --save mongoose
npm i --save @types/node
npm i --save ejs
npm i --save body-parser
npm i --save-dev @types/dotenv
npm i --save-dev @types/express
npm i --save-dev @types/mongoose